# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:36
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_admin_user'),
    ]

    operations = [
        UnaccentExtension()
    ]
