# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 16:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial_admin_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view user'),), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
