# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170919_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='edition date', null=True, verbose_name='updated at'),
        ),
    ]
