- name: check if DB exists
  # Note: get-db-config already verified that db_conf.NAME requires no quoting (Bobby Tables)
  shell: |
    if command -v psql >/dev/null; then
      psql --tuples-only --no-align \
        --username={{ db_conf.USER | quote }} \
        --host={{ db_conf.HOST | quote }} \
        --port={{ db_conf.PORT | quote }} \
        --dbname=postgres \
        --command="SELECT 1 FROM pg_database WHERE datname='{{ db_conf.NAME }}'"
    fi
  environment:
    PGPASSWORD: "{{ db_conf.PASSWORD }}"
  register: db_exists
  changed_when: false
