- name: Prepare
  hosts: all

  tasks:
    - name: set english environment locale
      import_tasks: ../utils/set-locale.yaml

    - name: Install Git   # required by geerlingguy.nodejs
      package:
        name: git
        state: present
      become: yes

    - name: install Node.js
      include_role:
        name: geerlingguy.nodejs
        apply:
          become: true
      vars:
        nodejs_version: 12.x
