- name: import DB
  hosts: all
  pre_tasks:
    - name: import check Ansible version task
      import_tasks: utils/assert-ansible-version.yaml

    - name: check that this playbook is run against a single host
      assert:
        that: ansible_play_hosts | length == 1
        fail_msg: You are trying to import the DB of several hosts at the same time.
        quiet: yes

  roles:
    - get-db-config

  tasks:
    - name: download remote dump
      block:
        - name: backup
          include_role:
            name: db
            tasks_from: backup

        - name: download
          include_role:
            name: db
            tasks_from: download
      when: local_dump is not defined

    - name: get local DB configuration
      include_role:
        name: get-db-config
        apply:
          delegate_to: localhost
      vars:
        on_localhost: yes

    - name: restore dump
      include_role:
        name: db
        tasks_from: restore
      vars:
        - dump_path: "{{ local_dump | default(inventory_hostname + '/' + dump_name) }}"
        - is_local_dump_file: "{{ local_dump is defined }}"
        - dest_delegate: localhost
