# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_auto_20180111_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['order'], 'verbose_name': 'region', 'verbose_name_plural': 'regions'},
        ),
    ]
