# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_auto_20180111_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='edition date', null=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='creation date', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='edition date', null=True, verbose_name='updated at'),
        ),
    ]
