# Generated by Django 2.2.15 on 2021-02-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='kind',
            field=models.CharField(choices=[('int', 'integer'), ('str', 'text'), ('time', 'time'), ('date', 'date'), ('json', 'json')], editable=False, max_length=255, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(editable=False, max_length=50, unique=True, verbose_name='name'),
        ),
    ]
